apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: astra-service
  labels:
    cloud.googleapis.com/location: europe-west1
spec:
  template:
    spec:
      containers:
        - image: europe-west1-docker.pkg.dev/yuyatinnefeld-dev/docker-repo/astro-image
          ports:
            - name: http1
              containerPort: 80